/**
 * Defines the optional parameters that control
 * how text is generated by an AI provider
 *
 * These map closely to common model configuration fields,
 * but can be extended by individual providers
 */
export interface IAIGenerationConfig {
  /**
   * The model identifier to use for generation
   */
  model?: string;

  /**
   * Additional provider-specific options for flexibility for 
   * future features or custom providers
   */
  [field: string]: any;
}
